### ISSUE TITLE
Location Suggestions not comming

### ISSUE THREAD

**Issue by saifkamaal** [superapp/react-native-location-view#3]
Hi,

Implemented this library however when i search for a location i dont see the list of suggestions coming up.

Google Places Key has been configured.
![simulator screen shot - iphone 6 - 2018-09-07 at 22 57 32](https://user-images.githubusercontent.com/29369768/45238029-6cfa3700-b2f1-11e8-9d79-b01b7351217c.png)

**Comment by hhunaid** [comment]
Are you sure you got the 'API Web Service' key?

**Comment by johnkingzy** [comment]
Hi @hhunaid, I don't think I understand what you mean by 'API Web Service' key because I'm currently having the same issue. Here's a list of enabled API from my google console. Am I missing anything?

Thank you.
<img width="431" alt="screen shot 2018-09-30 at 7 24 26 pm" src="https://user-images.githubusercontent.com/26271143/46259165-bef43e00-c4e6-11e8-937b-6593c3a5bbd0.png">

**Comment by hhunaid** [comment]
It's the [Google Places API](https://developers.google.com/places/web-service/get-api-key) key.
